### PR TITLE
Fix comparison html report bug

### PR DESCRIPTION
**Pull request by rundef**

### CODE REVIEW

**Comment by mmahut** [comment]
@matteofigus any change to get this merged?

**Comment by matteofigus** [comment]
Hi friends, apologies for the delay. I wrote this app a long time ago and I am not too familiar with the code anymore. Can you help me understanding a little bit more what's the bug that is been fixed? It's hard to grasp by just looking at the diff. Perhaps you can share a screenshot?

**Comment by mmahut** [comment]
hey @matteofigus I think this PR is related to this bug https://github.com/matteofigus/api-benchmark/issues/30

**Comment by matteofigus** [comment]
Ok merged and published, sorry for the delay!

**Pull request merged**
